# Generated by Django 4.2.9 on 2024-01-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_injury_uid_remove_player_uid_remove_team_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='injury',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
